import { useEffect } from "react"
import { Row, Col, Container } from "react-bootstrap"

export default function Home()
{
    useEffect(() => {document.title = "Elan Gabor"})

    return (<>
        <Container>
            <h2>Home</h2>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
            <p>duplicate!</p>
        </Container>
    </>)
}
