name: GitHub Pages Deployment

on:
    push:
        branches:
            [pre_deploy]

# needs proper permission to write to github pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
        
            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                node-version: 22

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build
            
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                name: 'github-pages'
                path: './build/'

            - name: Deploy to Github Pages
              uses: actions/deploy-pages@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                artifact_name: 'github-pages' 