name: Deploy React.js website to github pages

on:
    push:
        branches:
            - pre_deploy

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
        
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: "22"

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build
            
            - name: Deploy
              run: npm run deploy
