name: GitHub Pages Deployment

on:
    push:
        branches:
            - pre_deploy

permissions:
  contents: write

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
        
            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                node-version: '22'

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Deploy to a new branch with contents as build
              uses: JamesIves/github-pages-deploy@v4
              with:
                folder: build
                branch: gh-pages

              