name: Deploy React.js website to github pages

on:
    push:
        branches:
            - pre_deploy

jobs:
    dependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                node-version: 22
                cache: 'npm'
    build:
        needs: dependencies
        runs-on: ubuntu-latest
        steps:
            
            - name: Checkout
              uses: actions/checkout@v5
            
            - name: Install Dependencies and Build
              run: |
                npm ci
                npm run build

            - name: Upload Artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                path: build/
        
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: build
        permissions:
            pages: write
            id-token: write            
        runs-on: ubuntu-latest
        steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
          