name: "Deploy React.js website to github pages"

# Since this isn't the main branch, need to make this branch the default branch on github in settings
# currently runs manually with `workflow_dispatch`, even though pre_deploy is default branch the push-branches-pre_deploy isn't running
# it also appears that if I don't change the workflow file, then the recent checkout changes are ignored

on: workflow_dispatch 
  # push:
  #      branches:
  #          - pre_deploy

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                node-version: 22
                cache: 'npm'

            - name: Install Dependencies and Build
              id: build
              run: |
                npm ci
                npm run build

            - name: Upload Artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                path: build/
        
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: build
        permissions:
            contents: read
            pages: write
            id-token: write            
        runs-on: ubuntu-latest
        steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
          